import Stdx

/-!
# Vectors from the proved machines

Writes, or checks, every step of the machines `Stdx/Json/` proves, into files beside the Zig code
they mirror. A Zig unit test requires the Zig machine to take the same steps, which is what ties
the proofs about the Lean machines to the Zig code (decision 28).

    lake exe vectors (--write | --check) <src/json directory>
-/
open Stdx.Json

/-- The octets each machine takes a step on: every value of an octet. -/
def octets : List Nat := List.range 256

/-- One step of the UTF-8 machine: its state as `Utf8`'s fields, the octet, and the fields after
it, or `refused`. -/
def utf8Line (q : Utf8.State) (b : Nat) : String :=
  let (needed, low, high) := q.fields
  match Utf8.step q b with
  | some q' =>
    let (needed', low', high') := q'.fields
    s!"{needed} {low} {high} {b} {needed'} {low'} {high'}"
  | none => s!"{needed} {low} {high} {b} refused"

/-- Every step of the UTF-8 machine, from every state it reaches. -/
def utf8Lines : List String :=
  "# needed low high octet, then needed low high after it or refused: every octet from every state \
    of spec/lean/Stdx/Json/Utf8.lean, which starts at 0 128 191. Generated by \
    spec/lean/Vectors.lean; do not edit." ::
    Utf8.State.all.flatMap fun q => octets.map (utf8Line q)

/-- A verdict of the number machine, as `number_vectors.txt` spells it. -/
def verdictText : Number.Verdict → String
  | .taken q => s!"taken {q.name}"
  | .ended => "ended"
  | .invalid => "invalid"

/-- Whether each state is whole, then every verdict of the number machine, from every state. -/
def numberLines : List String :=
  "# whole state 0|1, then accept state octet verdict [state after]: every octet from every state \
    of spec/lean/Stdx/Json/Number.lean. Generated by spec/lean/Vectors.lean; do not edit." ::
    (Number.State.all.map fun q => s!"whole {q.name} {if Number.whole q then 1 else 0}") ++
    Number.State.all.flatMap fun q =>
      octets.map fun b => s!"accept {q.name} {b} {verdictText (Number.accept q b)}"

/-- Each vector file and its lines. -/
def files : List (String × List String) :=
  [("utf8_vectors.txt", utf8Lines), ("number_vectors.txt", numberLines)]

/-- Writes each file, or checks each against what the machines give; 1 when one differs. -/
def main (arguments : List String) : IO UInt32 := do
  let usage := "usage: vectors (--write | --check) <src/json directory>"
  let [mode, directory] := arguments | IO.eprintln usage; return 2
  unless mode == "--write" || mode == "--check" do
    IO.eprintln usage
    return 2
  let mut status : UInt32 := 0
  for (name, lines) in files do
    let path := System.FilePath.mk directory / name
    let text := "\n".intercalate lines ++ "\n"
    if mode == "--write" then
      IO.FS.writeFile path text
    else if (← IO.FS.readFile path) != text then
      IO.eprintln s!"{path}: not what the proved machines give; run `zig build lean -- write`"
      status := 1
  return status
